# configuration for objects and agents, add scene as well
task_name: TakePhoto
scene:
  name: Table
  env:
    floor_width: 100
  primitives:
    - 
      name: cube
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.06
        color: [0.5, 0.5, 0.5, 1]
        name: cube
        body_type: static
        initial_pose:
          p: [-0.05, -0.1, 0.03]
      pos:
        ppos:
          p: [-0.05, -0.1, 0.03]
          q: [0., 0., 1.5707963268]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0.1, 0.2, 0.]
        randq_scale: [0., 0., 0., 0.]
  assets: 
    - name: table
      file_path: assets/scenes/table/table.glb
      collision:
        type: box
        pos:
          p: [0, 0, 0.45982145]
          half_size: [3.0225, 1.51125, 0.45982145]
      pos: 
        ppos:
          p: [-0.12, 0., -0.9196429]
          q: [0., 0., 1.5707963268]
        randp_scale: [0., 0., 0.]
        randq_scale: [0., 0., 0., 0.]
      scale: [4.375, 4.375, 1.75]
    
objects:
  -
    name: camera
    file_path: assets/objects/camera_annotated/textured.obj
    annotation_path: assets/objects/camera_annotated/model_data.json
    material: 
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.
    visual:
      filename: assets/objects/camera_annotated/textured.obj
      scale: [0.25, 0.25, 0.25]
    collision:
      type: convex
      filename: assets/objects/camera_annotated/textured.obj
      scale: [0.25, 0.25, 0.25]
    pos:
      ppos:
        p: [-0.05, -0.1, 0.089]
      qpos: [0.718, 0.012, 0.015, 0.696]
      randp_scale: [0.1, 0.2, 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 0.01
      cmass_local_pose: [0., 0., 0.]
      inertia: [0., 0., 0.]
  -
    name: meat
    file_path: assets/objects/meat_annotated/textured.obj
    annotation_path: assets/objects/meat_annotated/model_data.json
    material: 
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.
    visual:
      filename: assets/objects/meat_annotated/textured.obj
      scale: [0.08, 0.4, 0.08]
    collision:
      type: convex
      filename: assets/objects/meat_annotated/textured.obj
      scale: [0.08, 0.4, 0.08]
    pos:
      ppos:
        p: [0.45, -0.4, 0.]
      qpos: [0.014, 0.065, 0.052, 0.996]
      randp_scale: [0.15, 0.2, 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 0.005
      cmass_local_pose: [0., 0., 0.]
      inertia: [0.1, 0.1, 0.1]

agents:
  -
    robot_uid: panda-0
    pos:
      ppos:
        p: [0., -0.85, 0.]
        q: [0., 0., 1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda-1
    pos:
      ppos:
        p: [0., 0.85, 0.]
        q: [0., 0., -1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda-2
    pos:
      ppos:
        p: [1., 0., 0.]
        q: [0., 0., 3.1415926536]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda-3
    pos:
      ppos:
        p: [-0.6, 0., 0.]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.1780972451, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera_agent0
      pose:
        type: pose
        params: [[-0.517379, -0.825534, 0.544694], [0.973373, -0.0263478, 0.148767, 0.172391]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 100
    - 
      uid: head_camera_agent1
      pose:
        type: pose
        params: [[0.562348, 0.785704, 0.555279], [0.161394, 0.131976, 0.0217843, -0.977783]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 100
    - 
      uid: head_camera_agent2
      pose:
        type: pose
        params: [[0.827632, -0.75711, 0.520754], [0.692724, -0.0746079, 0.0724179, 0.713668]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 100
    - 
      uid: head_camera_agent3
      pose:
        type: pose
        params: [[-0.70417, 0.458536, 0.606336], [0.871062, 0.053639, 0.0976719, -0.478366]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 100
    - 
      uid: head_camera_global
      pose:
        type: pose
        params: [[0.672536, -0.794409, 0.694811], [0.42276, -0.258701, 0.127348, 0.859145]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 100
  human_render:
    - 
      uid: render_camera
      pose:
        type: look_at
        params: [[0.6, 0.7, 0.6], [0., 0., 0.35]]
      width: 3840
      height: 2160
      fov: 1
      near: 0.01
      far: 10